<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS Test database</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>c562b6bb-e3b0-4f77-a6ec-6070303144f4</testSuiteGuid>
   <testCaseLink>
      <guid>45d87981-22f7-48a4-852a-4d65232f651a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>findTestData(null)</defaultValue>
         <description></description>
         <id>e5a74b2e-245f-4edb-937a-73ac8c7532a6</id>
         <masked>false</masked>
         <name>variable</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/TC CURA/TC My Cura</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>0a65bb1d-610b-455b-a59e-05c9afc1533f</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DB Test data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>0a65bb1d-610b-455b-a59e-05c9afc1533f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>e5a74b2e-245f-4edb-937a-73ac8c7532a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0a65bb1d-610b-455b-a59e-05c9afc1533f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>04c3615b-a8fa-49aa-9793-ed0499d5f89c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
